version: '3'

services:

  api:
    container_name: flask_prod_api
    restart: always
    build: ./api
    ports:
      - "8000:8000"
    command: gunicorn -w 3 -b :8000 app:app

  nginx:
    container_name: nginx
    restart: always
    build: ./nginx
    ports:
      - "8001:8001"
    depends_on:
      - api